### ISSUE TITLE
Assignment 1 Question - Stochastic vs. deteministic

### ISSUE THREAD

**Issue by gmvelez** [UC-MACSS/persp-model_W18#1]
Hi,

I was just wondering if you could explain a little bit the difference between these two.  If a model has an error term, that would be randomly distributed, and so would it be stochastic?  If we are applying it to a dataset and using linear regression with variables we know, is it then deterministic?

Thanks!

**Comment by rickecon** [comment]
@gmvelez. Deterministic models are models in which the characterizing equations have no random variables--neither explicit random variables nor implicit random variables. For example any regression model either implicitly or explicitly assumes a stochastic model because it requires an error term to make the right-hand-side equal the left-hand-side. Some theoretical models are deterministic and have no random variables.

**Comment by gmvelez** [comment]
Great - thank you!
